//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrosEDM.ModeloAplicacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.AlquilerDeLibro = new HashSet<AlquilerDeLibro>();
        }
    
        public int Id { get; set; }
        public string CodigoDelCliente { get; set; }
        public string NombresDelCliente { get; set; }
        public string ApellidosDelCliente { get; set; }
        public int TipoDeClienteId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlquilerDeLibro> AlquilerDeLibro { get; set; }
        public virtual TipoDeCliente TipoDeCliente { get; set; }
    }
}
