//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrosEDM.ModeloAplicacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class CopiaLibro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CopiaLibro()
        {
            this.AlquilerDeLibro = new HashSet<PrestamoLibro>();
        }
    
        public int Id { get; set; }
        public int NumeroDeCopia { get; set; }
        public int EstadoDelLibroId { get; set; }
        public int LibroId { get; set; }
    
        public virtual EstadoLibro EstadoDelLibro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrestamoLibro> AlquilerDeLibro { get; set; }
        public virtual Libro Libro { get; set; }
    }
}
