//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrosEDM.ModeloAplicacion
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LibrosModelContainer : DbContext
    {
        public LibrosModelContainer()
            : base("name=LibrosModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Materia> Materias { get; set; }
        public virtual DbSet<Idioma> Idiomas { get; set; }
        public virtual DbSet<Editorial> Editoriales { get; set; }
        public virtual DbSet<EstadoLibro> EstadosDelLibro { get; set; }
        public virtual DbSet<Libro> Libros { get; set; }
        public virtual DbSet<Autor> Autores { get; set; }
        public virtual DbSet<DetalleDeAutor> DetallesDeAutor { get; set; }
        public virtual DbSet<CopiaLibro> CopiasDeLibro { get; set; }
        public virtual DbSet<PrestamoLibro> AlquileresDeLibro { get; set; }
        public virtual DbSet<Estudiante> Clientes { get; set; }
    
        public virtual ObjectResult<usp_BuscarCliente_Result> usp_BuscarCliente(string nom, string ape)
        {
            var nomParameter = nom != null ?
                new ObjectParameter("Nom", nom) :
                new ObjectParameter("Nom", typeof(string));
    
            var apeParameter = ape != null ?
                new ObjectParameter("Ape", ape) :
                new ObjectParameter("Ape", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_BuscarCliente_Result>("usp_BuscarCliente", nomParameter, apeParameter);
        }
    
        public virtual ObjectResult<usp_ObtenerAlqClte_Result> usp_ObtenerAlqClte(Nullable<int> idCliente)
        {
            var idClienteParameter = idCliente.HasValue ?
                new ObjectParameter("idCliente", idCliente) :
                new ObjectParameter("idCliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ObtenerAlqClte_Result>("usp_ObtenerAlqClte", idClienteParameter);
        }
    }
}
