//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrosEDM.ModeloAplicacion
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LibrosModelContainer : DbContext
    {
        public LibrosModelContainer()
            : base("name=LibrosModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Materia> Materias { get; set; }
        public virtual DbSet<Idioma> Idiomas { get; set; }
        public virtual DbSet<Editorial> Editoriales { get; set; }
        public virtual DbSet<TipoDeCliente> TiposDeCliente { get; set; }
        public virtual DbSet<EstadoDelLibro> EstadosDelLibro { get; set; }
        public virtual DbSet<Libro> Libros { get; set; }
        public virtual DbSet<Autor> Autores { get; set; }
        public virtual DbSet<DetalleDeAutor> DetallesDeAutor { get; set; }
        public virtual DbSet<CopiaDeLibro> CopiasDeLibro { get; set; }
        public virtual DbSet<AlquilerDeLibro> AlquileresDeLibro { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
    
        public virtual ObjectResult<usp_BuscarCliente_Result> usp_BuscarCliente(string nomb, string ape)
        {
            var nombParameter = nomb != null ?
                new ObjectParameter("nomb", nomb) :
                new ObjectParameter("nomb", typeof(string));
    
            var apeParameter = ape != null ?
                new ObjectParameter("ape", ape) :
                new ObjectParameter("ape", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_BuscarCliente_Result>("usp_BuscarCliente", nombParameter, apeParameter);
        }
    
        public virtual ObjectResult<usp_ObtenerAlqClte_Result> usp_ObtenerAlqClte(Nullable<int> idCliente)
        {
            var idClienteParameter = idCliente.HasValue ?
                new ObjectParameter("idCliente", idCliente) :
                new ObjectParameter("idCliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ObtenerAlqClte_Result>("usp_ObtenerAlqClte", idClienteParameter);
        }
    }
}
